### ISSUE TITLE
Please make text concave to ease the print

### ISSUE THREAD

**Issue by TzOk83** [prcoder-1/MiSTeryNano-Case#1]
I've just printed this case and it fits well. I have put the case upside down, and sunk the print into the print bed in the slicer, to get a flat top surface. This let me print the whole case without a single support structure.

**Comment by prcoder-1** [comment]
Ok. I added this version too.

https://github.com/prcoder-1/MiSTeryNano-Case/blob/main/USB-C%20Breakout-Case%20(embossed).stl

And I'm trying to print it now.
